name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/demographic_parameters --tag islasgeci/demographic_parameters:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/demographic_parameters make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/demographic_parameters make coverage
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@main
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
